### ISSUE TITLE
Mangagezgini changed thema and domain

### ISSUE THREAD

**Issue by Thekages** [kitsumed/mihonyomi-extensions#22]
### Source information

MangaGezgini 1.4.38

### Source language

Turkish

### Steps to reproduce

Mangagezgini.com changed https://noxscans.com/ and changed thema

### Expected behavior

Opened

### Actual behavior

Notopened

### Tachiyomi compatible app name & version

Mihon 0.16.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the tachiyomi compatible app.
- [X] I have the latest extension version.
- [X] I will fill out all of the requested information in this form.

**Comment by kitsumed** [comment]
Hi @Thekages.
This repo only support extension that communicate with self-hosted servers. Please ask the right repo.
